version: "3.9"
services:
  uti-mock:
    build: .
    container_name: uti-mock
    environment:
      BASIC_USER: "usuario"
      BASIC_PASS: "contrasena"
      TZ: "America/Argentina/Cordoba"
    ports:
      - "8088:8000"
    restart: unless-stopped
    networks:
      - devnet

networks:
  devnet:
    external: true


